### ISSUE TITLE
[학습] Lambda의 가능성 확인

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Backend#3]
## GOAL
- 람다로 어디까지 대체 가능한지 확인해보기
- Figjam에서 하트가 붙은 항목들에 대해 체크
- 람다 코드의 경우 완수하실 때 마다 코드 전문을 댓글로 남겨주세요!!
## TODO
- [x] #19

- [x] #20

- [x] #21

**Comment by joybully** [comment]
https://aws.amazon.com/ko/sqs/
sqs란?

Lambda란?->함수다(자동으로 동작)
이벤트 발생시 코드를 실행함
이벤트 예시->로그, 클라이언트의 요청
동적인 웹 서비스를 Lambda로 가능함
S3의 트리거, SQS의 메시지 수신등도 Lambda로 가능함
클라이언트->API 게이트웨이->AWS람다<->DB
Lambda는 함수의 실행시간과 용량을 기준으로 과금
lambda함수는 aws academy에서는 안되나?

RDS란?
관계형 데이터베이스 서비스
EC2를 기반으로 제공되는 서비스

**Comment by joybully** [comment]
aws academy lambda function 에러
User: arn:aws:sts::505697769335:assumed-role/voclabs/user1972373=joybully@khu.ac.kr is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::505697769335:role/service-role/pythonlambdajoybully-role-xf6r1xum because no identity-based policy allows the iam:CreateRole action

**Comment by joybully** [comment]
IAM계정 생성도 불가->권한 설정 안됨

**Comment by joybully** [comment]
전역 큐에서 만료된 그라운드를 꺼낸 SQS
원본 이미지는 무거우니까 해상도를 줄인 이미지 생성(미리보기 이미지 생성)
RDS에 해당 그라운드가 갖고 있는 사진 정보 추가(데이터베이스 갱신)
그라운드 SQS 보내기->그라운드 id를 SQS로 보내는 건가?

**Comment by gene-ss** [comment]
확인했습니다~ 위의 람다 함수 3가지 작성하는거 각각 이슈로 변경하고 담당자 등록해두겠습니다.
